package br.com.helpdev.githubers

const val JSON_USER = "{\n" +
        "\"login\": \"mojombo\",\n" +
        "\"id\": 1,\n" +
        "\"node_id\": \"MDQ6VXNlcjE=\",\n" +
        "\"avatar_url\": \"https://avatars0.githubusercontent.com/u/1?v=4\",\n" +
        "\"gravatar_id\": \"\",\n" +
        "\"url\": \"https://api.github.com/users/mojombo\",\n" +
        "\"html_url\": \"https://github.com/mojombo\",\n" +
        "\"followers_url\": \"https://api.github.com/users/mojombo/followers\",\n" +
        "\"following_url\": \"https://api.github.com/users/mojombo/following{/other_user}\",\n" +
        "\"gists_url\": \"https://api.github.com/users/mojombo/gists{/gist_id}\",\n" +
        "\"starred_url\": \"https://api.github.com/users/mojombo/starred{/owner}{/repo}\",\n" +
        "\"subscriptions_url\": \"https://api.github.com/users/mojombo/subscriptions\",\n" +
        "\"organizations_url\": \"https://api.github.com/users/mojombo/orgs\",\n" +
        "\"repos_url\": \"https://api.github.com/users/mojombo/repos\",\n" +
        "\"events_url\": \"https://api.github.com/users/mojombo/events{/privacy}\",\n" +
        "\"received_events_url\": \"https://api.github.com/users/mojombo/received_events\",\n" +
        "\"type\": \"User\",\n" +
        "\"site_admin\": false\n" +
        "}"

const val JSON_USER_DETAILS = "{\n" +
        "\"login\": \"mojombo\",\n" +
        "\"id\": 1,\n" +
        "\"node_id\": \"MDQ6VXNlcjE=\",\n" +
        "\"avatar_url\": \"https://avatars0.githubusercontent.com/u/1?v=4\",\n" +
        "\"gravatar_id\": \"\",\n" +
        "\"url\": \"https://api.github.com/users/mojombo\",\n" +
        "\"html_url\": \"https://github.com/mojombo\",\n" +
        "\"followers_url\": \"https://api.github.com/users/mojombo/followers\",\n" +
        "\"following_url\": \"https://api.github.com/users/mojombo/following{/other_user}\",\n" +
        "\"gists_url\": \"https://api.github.com/users/mojombo/gists{/gist_id}\",\n" +
        "\"starred_url\": \"https://api.github.com/users/mojombo/starred{/owner}{/repo}\",\n" +
        "\"subscriptions_url\": \"https://api.github.com/users/mojombo/subscriptions\",\n" +
        "\"organizations_url\": \"https://api.github.com/users/mojombo/orgs\",\n" +
        "\"repos_url\": \"https://api.github.com/users/mojombo/repos\",\n" +
        "\"events_url\": \"https://api.github.com/users/mojombo/events{/privacy}\",\n" +
        "\"received_events_url\": \"https://api.github.com/users/mojombo/received_events\",\n" +
        "\"type\": \"User\",\n" +
        "\"site_admin\": false,\n" +
        "\"name\": \"Tom Preston-Werner\",\n" +
        "\"company\": null,\n" +
        "\"blog\": \"http://tom.preston-werner.com\",\n" +
        "\"location\": \"San Francisco\",\n" +
        "\"email\": null,\n" +
        "\"hireable\": null,\n" +
        "\"bio\": null,\n" +
        "\"public_repos\": 61,\n" +
        "\"public_gists\": 62,\n" +
        "\"followers\": 21333,\n" +
        "\"following\": 11,\n" +
        "\"created_at\": \"2007-10-20T05:24:19Z\",\n" +
        "\"updated_at\": \"2018-12-18T19:52:12Z\"\n" +
        "}"

const val JSON_USER_REPO_1 = "{\n" +
        "\"id\": 26899533,\n" +
        "\"node_id\": \"MDEwOlJlcG9zaXRvcnkyNjg5OTUzMw==\",\n" +
        "\"name\": \"30daysoflaptops.github.io\",\n" +
        "\"full_name\": \"mojombo/30daysoflaptops.github.io\",\n" +
        "\"private\": false,\n" +
        "\"owner\": {\n" +
        "\"login\": \"mojombo\",\n" +
        "\"id\": 1,\n" +
        "\"node_id\": \"MDQ6VXNlcjE=\",\n" +
        "\"avatar_url\": \"https://avatars0.githubusercontent.com/u/1?v=4\",\n" +
        "\"gravatar_id\": \"\",\n" +
        "\"url\": \"https://api.github.com/users/mojombo\",\n" +
        "\"html_url\": \"https://github.com/mojombo\",\n" +
        "\"followers_url\": \"https://api.github.com/users/mojombo/followers\",\n" +
        "\"following_url\": \"https://api.github.com/users/mojombo/following{/other_user}\",\n" +
        "\"gists_url\": \"https://api.github.com/users/mojombo/gists{/gist_id}\",\n" +
        "\"starred_url\": \"https://api.github.com/users/mojombo/starred{/owner}{/repo}\",\n" +
        "\"subscriptions_url\": \"https://api.github.com/users/mojombo/subscriptions\",\n" +
        "\"organizations_url\": \"https://api.github.com/users/mojombo/orgs\",\n" +
        "\"repos_url\": \"https://api.github.com/users/mojombo/repos\",\n" +
        "\"events_url\": \"https://api.github.com/users/mojombo/events{/privacy}\",\n" +
        "\"received_events_url\": \"https://api.github.com/users/mojombo/received_events\",\n" +
        "\"type\": \"User\",\n" +
        "\"site_admin\": false\n" +
        "},\n" +
        "\"html_url\": \"https://github.com/mojombo/30daysoflaptops.github.io\",\n" +
        "\"description\": null,\n" +
        "\"fork\": true,\n" +
        "\"url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io\",\n" +
        "\"forks_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/forks\",\n" +
        "\"keys_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/keys{/key_id}\",\n" +
        "\"collaborators_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/collaborators{/collaborator}\",\n" +
        "\"teams_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/teams\",\n" +
        "\"hooks_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/hooks\",\n" +
        "\"issue_events_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues/events{/number}\",\n" +
        "\"events_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/events\",\n" +
        "\"assignees_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/assignees{/user}\",\n" +
        "\"branches_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/branches{/branch}\",\n" +
        "\"tags_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/tags\",\n" +
        "\"blobs_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/blobs{/sha}\",\n" +
        "\"git_tags_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/tags{/sha}\",\n" +
        "\"git_refs_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/refs{/sha}\",\n" +
        "\"trees_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/trees{/sha}\",\n" +
        "\"statuses_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/statuses/{sha}\",\n" +
        "\"languages_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/languages\",\n" +
        "\"stargazers_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/stargazers\",\n" +
        "\"contributors_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/contributors\",\n" +
        "\"subscribers_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/subscribers\",\n" +
        "\"subscription_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/subscription\",\n" +
        "\"commits_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits{/sha}\",\n" +
        "\"git_commits_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/commits{/sha}\",\n" +
        "\"comments_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/comments{/number}\",\n" +
        "\"issue_comment_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues/comments{/number}\",\n" +
        "\"contents_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/contents/{+path}\",\n" +
        "\"compare_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/compare/{base}...{head}\",\n" +
        "\"merges_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/merges\",\n" +
        "\"archive_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/{archive_format}{/ref}\",\n" +
        "\"downloads_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/downloads\",\n" +
        "\"issues_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues{/number}\",\n" +
        "\"pulls_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/pulls{/number}\",\n" +
        "\"milestones_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/milestones{/number}\",\n" +
        "\"notifications_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/notifications{?since,all,participating}\",\n" +
        "\"labels_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/labels{/name}\",\n" +
        "\"releases_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/releases{/id}\",\n" +
        "\"deployments_url\": \"https://api.github.com/repos/mojombo/30daysoflaptops.github.io/deployments\",\n" +
        "\"created_at\": \"2014-11-20T06:42:06Z\",\n" +
        "\"updated_at\": \"2018-12-12T00:39:06Z\",\n" +
        "\"pushed_at\": \"2014-11-20T06:42:47Z\",\n" +
        "\"git_url\": \"git://github.com/mojombo/30daysoflaptops.github.io.git\",\n" +
        "\"ssh_url\": \"git@github.com:mojombo/30daysoflaptops.github.io.git\",\n" +
        "\"clone_url\": \"https://github.com/mojombo/30daysoflaptops.github.io.git\",\n" +
        "\"svn_url\": \"https://github.com/mojombo/30daysoflaptops.github.io\",\n" +
        "\"homepage\": null,\n" +
        "\"size\": 1197,\n" +
        "\"stargazers_count\": 4,\n" +
        "\"watchers_count\": 4,\n" +
        "\"language\": \"CSS\",\n" +
        "\"has_issues\": false,\n" +
        "\"has_projects\": true,\n" +
        "\"has_downloads\": true,\n" +
        "\"has_wiki\": true,\n" +
        "\"has_pages\": false,\n" +
        "\"forks_count\": 2,\n" +
        "\"mirror_url\": null,\n" +
        "\"archived\": false,\n" +
        "\"open_issues_count\": 0,\n" +
        "\"license\": null,\n" +
        "\"forks\": 2,\n" +
        "\"open_issues\": 0,\n" +
        "\"watchers\": 4,\n" +
        "\"default_branch\": \"gh-pages\"\n" +
        "}"